[project]
name = "gpt-2-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "jupyter>=1.1.1",
    "lab>=8.5",
    "regex>=2025.11.3",
]
